version: '3.8'
services:
  app:
    build: .
    environment:
      - GETBLOCK_API_KEY=${GETBLOCK_API_KEY}
      - ENV=${ENV}
      - DebugLevel=${DebugLevel}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
